In [6]:
import numpy as np

#### 1. Write a function, foo_1, that takes a NumPy array `arr` and returns the indices of the elements that are closest to a given target. If target is not in the given array, it should return ‘no item found’

In [7]:
def foo_1(arr, target):
    if target in arr:
        x=np.abs(arr - target) 
        index = np.argsort(x) 
        return index 
    else:
        return 'no item found'

In [8]:
arr = np.array([3, 8, 7, 7, 7, 7, 7, 8, 7, 10])

print(foo_1(arr, 7))

print(foo_1(arr, 11))

[2 3 4 5 6 8 1 7 9 0]
no item found


Import NumPy: import numpy as np imports the NumPy library and gives it the alias np for convenience.

Function Definition: The foo_1 function takes two parameters - arr (NumPy array) and target (the target value to find in the array).

Check if Target in Array: The if target in arr statement checks whether the target value is present in the array. If it is, the function proceeds; otherwise, it returns the string 'no item found'.

Calculate Absolute Differences: x = np.abs(arr - target) calculates the absolute differences between each element in the array arr and the target value.

Sort Indices: index = np.argsort(x) returns the indices that would sort the array x in ascending order.

Create Result Array: result = np.array(list(zip(arr[index], index))) creates a result array by zipping the original array elements at the sorted indices. The result is a 2D array where the first column contains the original array elements, and the second column contains the corresponding sorted indices.

Return Result: The function returns the result array if the target is found in the array; otherwise, it returns the string 'no item found'.

#### 3.1 You are given a 2D NumPy array of data representing student scores. Each row represents a student, and each column represents a subject. Extract the scores of all students who scored above 90 in at least one subject. Provide the resulting array.

In [9]:
def foo_marks(scores):
    x = np.any(scores > 90, axis=1)
    result = scores[x]
    return result

In [10]:
student_score = np.array([[85, 89, 88],
                 [78, 89, 94],
                 [91, 87, 90],
                 [87, 95, 84]])

In [11]:
foo_marks(student_score)

array([[78, 89, 94],
       [91, 87, 90],
       [87, 95, 84]])

np.any(scores > 90, axis=1):

This line creates a boolean array x by using NumPy's any function along axis=1. It checks for each row (student) whether there is any score greater than 90 in any subject. The resulting boolean array has True where the condition is met (at least one subject score is greater than 90) and False otherwise.

result = scores[x]:

This line creates a subset of the original array scores by using the boolean array x as a mask. It selects only those rows (students) where the corresponding element in x is True. In other words, it includes only the rows where at least one subject score is above 90.
Return Result:

The function returns the resulting array, which includes only those rows (students) where at least one subject score is above 90.

#### 3.2 You are provided with a 2D NumPy array of data representing sales data for different products. Each row corresponds to a product, and each column represents the monthly sales for a specific month. Calculate the following statistics for each product: mean, median, standard deviation, and the month with the highest sales.


In [12]:
def foo(sales_data):
    sd = {}
    for x, y in enumerate(sales_data):
        mean_sales = np.mean(y)
        median_sales = np.median(y)
        std_dev_sales = np.std(y)
        highest_sales_month = np.argmax(y) + 1
        sd[x + 1] = {
            'mean': mean_sales,
            'median': median_sales,
            'std_dev': std_dev_sales,
            'highest_sales_month': highest_sales_month
        }
    return sd

Initialize an Empty Dictionary sd:

sd = {} initializes an empty dictionary sd to store the calculated statistics for each product.

Iterate Over Each Row (Product) in sales_data:

for x, y in enumerate(sales_data): uses the enumerate function to iterate over each row (y) in sales_data. The variable x represents the index of the current row (product).

Calculate Statistics for Each Product:

Inside the loop, the following statistics are calculated for each product (row):
mean_sales: The mean of sales for the current product (np.mean(y)).
median_sales: The median of sales for the current product (np.median(y)).
std_dev_sales: The standard deviation of sales for the current product (np.std(y)).
highest_sales_month: The month with the highest sales for the current product (np.argmax(y) + 1 to convert to 1-based indexing).

Store Results in the Dictionary sd:

The calculated statistics for each product are stored in the dictionary sd. The key is the product index (x + 1 to convert to 1-based indexing), and the value is another dictionary containing the calculated statistics.
Return the Resulting Dictionary sd:

The function returns the final dictionary sd containing statistics for each product.

In [13]:
sales_data=np.array([[120, 150, 130, 110],
                    [200, 180, 220, 250],
                    [90, 100, 95, 110],
                    [300,280,320, 340]])

In [14]:
foo(sales_data)

{1: {'mean': 127.5,
  'median': 125.0,
  'std_dev': 14.79019945774904,
  'highest_sales_month': 2},
 2: {'mean': 212.5,
  'median': 210.0,
  'std_dev': 25.8602010819715,
  'highest_sales_month': 4},
 3: {'mean': 98.75,
  'median': 97.5,
  'std_dev': 7.39509972887452,
  'highest_sales_month': 4},
 4: {'mean': 310.0,
  'median': 310.0,
  'std_dev': 22.360679774997898,
  'highest_sales_month': 4}}

#### 3.3 Create a NumPy array of size 1000 with random integers between 1 and 100. Then, use NumPy functions to find the top 10 most frequently occurring values in the array.

In [15]:
def freq(x):
    unique_values, counts = np.unique(x, return_counts=True)
    sorted = np.argsort(-counts)
    top_10_values = unique_values[sorted[:10]]
    top_10_counts = counts[sorted[:10]] 
    print("Top 10 most frequently occurring values:")
    for value, count in zip(top_10_values, top_10_counts):
        print(f"Value: {value}, Occurrences: {count}")

unique_values, counts = np.unique(x, return_counts=True):

This line uses NumPy's unique function to find the unique values in the array x along with their counts.

sorted_indices = np.argsort(-counts):

The indices are sorted in descending order based on the counts using argsort. The negative sign (-) is used to sort in descending order.

In [16]:
x=np.random.randint(1,100,1000)
x

array([57, 10,  8, 69, 81, 84, 29, 44, 55,  7, 76, 88, 10, 88,  7, 87, 93,
       86, 25, 93, 31, 31, 68, 32, 83, 74, 91, 32, 62, 60, 17, 85, 89, 36,
       48, 45, 80, 25, 99, 31,  7, 98, 27, 40, 20,  5, 37, 96, 71, 93, 75,
       19, 28, 76, 48, 33, 57, 33, 63, 34,  7, 21, 24, 23, 84, 46, 57, 22,
       93, 50, 81, 98, 31, 76, 70, 27, 98, 23, 40,  1, 40, 32, 88, 63, 67,
        3, 23, 69, 98, 31,  5, 50, 55, 34, 71, 32, 15, 86, 24, 52, 59, 17,
       37, 31, 42, 81, 69, 11, 88, 33, 55, 85, 72, 89, 51, 93, 90, 95,  5,
       19, 35, 51, 57, 39, 76, 53,  1, 73, 85, 17, 13, 22, 20, 97, 73, 87,
       67, 12, 76, 60, 57, 56, 45, 82,  5, 75, 71, 94, 51, 59,  4, 50, 55,
       39, 87, 46, 24, 62, 26, 18, 56, 29, 86, 40,  3, 75, 46, 23, 59, 11,
       71, 80,  3, 87, 39, 14, 97, 74, 48, 87,  3,  6, 63, 90, 85, 49, 40,
       61, 31, 90, 81,  4, 98, 30, 49, 42, 21, 84, 14, 83, 18, 95,  4, 78,
        4,  2, 14, 10, 35, 33,  8, 98, 81, 53, 44, 75, 29, 74, 99, 11, 63,
       28, 36, 29, 64, 59

In [17]:
freq(x)

Top 10 most frequently occurring values:
Value: 5, Occurrences: 20
Value: 57, Occurrences: 18
Value: 69, Occurrences: 16
Value: 40, Occurrences: 16
Value: 60, Occurrences: 16
Value: 7, Occurrences: 16
Value: 36, Occurrences: 16
Value: 25, Occurrences: 15
Value: 71, Occurrences: 15
Value: 88, Occurrences: 15
